// Authentication and Authorization
export const SET_USER = "SET_USER";
export const REMOVE_USER_DATA = "REMOVE_USER_DATA";
export const GET_USER_DATA = "GET_USER_DATA";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const REGISTER_ERROR = "REGISTER_ERROR";
export const SOCIAL_ERROR = "SOCIAL_ERROR";
export const TOGGLE_IS_LOADING_USER_DATA = "TOGGLE_IS_LOADING_USER_DATA";
export const TOGGLE_IS_LOADING_AUTH_USER = "TOGGLE_IS_LOADING_AUTH_USER";
export const TOGGLE_IS_UPDATING_USER_DATA = "TOGGLE_IS_UPDATING_USER_DATA";

// Movie Listings
export const GET_DISCOVER_MOVIE_LIST = "GET_DISCOVER_MOVIE_LIST";
export const GET_FILTER_MOVIE_LIST = "GET_FILTER_MOVIE_LIST";
export const TOGGLE_IS_LOADING_MOVIE_LIST = "TOGGLE_IS_LOADING_MOVIE_LIST";

// Individual Movie Data
export const GET_MOVIE_DATA = "GET_MOVIE_DATA";
export const GET_CASTS_LIST = "GET_CASTS_LIST";
export const GET_REVIEWS_LIST = "GET_REVIEWS_LIST";
export const GET_REC_MOVIES_LIST = "GET_REC_MOVIES_LIST";
export const TOGGLE_IS_LOADING_MOVIE_DATA = "TOGGLE_IS_LOADING_MOVIE_DATA";
export const TOGGLE_IS_LOADING_CASTS_LIST = "TOGGLE_IS_LOADING_CASTS_LIST";
export const TOGGLE_IS_LOADING_REVIEWS_LIST = "TOGGLE_IS_LOADING_REVIEWS_LIST";
export const TOGGLE_IS_LOADING_REC_MOVIES_LIST =
  "TOGGLE_IS_LOADING_REC_MOVIES_LIST";

// Movie Home Page
export const GET_TRENDING_MOVIE = "GET_TRENDING_MOVIE";
export const GET_RECOMMENDED_MOVIE = "GET_RECOMMENDED_MOVIE";
export const GET_NOW_PLAYING_MOVIE = "GET_NOW_PLAYING_MOVIE";
export const TOGGLE_IS_LOADING_TRENDING_MOVIE =
  "TOGGLE_IS_LOADING_TRENDING_MOVIE";
export const TOGGLE_IS_LOADING_RECOMMENDED_MOVIE =
  "TOGGLE_IS_LOADING_RECOMMENDED_MOVIE";
export const TOGGLE_IS_LOADING_NOW_PLAYING_MOVIE =
  "TOGGLE_IS_LOADING_NOW_PLAYING_MOVIE";

// Celeb Info
export const GET_PERSON_DETAIL = "GET_PERSON_DETAIL";
export const GET_KNOWN_FOR = "GET_KNOWN_FOR";
export const TOGGLE_IS_LOADING_KNOWN_FOR = "TOGGLE_IS_LOADING_KNOWN_FOR";
export const TOGGLE_IS_LOADING_PERSON_DETAIL =
  "TOGGLE_IS_LOADING_PERSON_DETAIL";

// Search Parameter
export const UPDATE_SEARCH_KEYWORD = "UPDATE_SEARCH_KEYWORD";
export const GET_SEARCH_SUGGESTION = "GET_SEARCH_SUGGESTION";
export const GET_SEARCH_RESULTS = "GET_SEARCH_RESULTS";
export const TOGGLE_IS_LOADING_SEARCH_SUGGESTION =
  "TOGGLE_IS_LOADING_SEARCH_SUGGESTION";
export const TOGGLE_IS_LOADING_SEARCH_RESULTS =
  "TOGGLE_IS_LOADING_SEARCH_RESULTS";
